-- MySQL Script generated by MySQL Workbench
-- Fri May  6 03:41:42 2022
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema luaWave
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `luaWave` ;

-- -----------------------------------------------------
-- Schema luaWave
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `luaWave` ;
-- -----------------------------------------------------
-- Schema luawave
-- -----------------------------------------------------
USE `luaWave` ;

-- -----------------------------------------------------
-- Table `luaWave`.`Articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luaWave`.`Articles` ;

CREATE TABLE IF NOT EXISTS `luaWave`.`Articles` (
  `Articles_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(500) NULL DEFAULT 'DEFAULT NULL',
  `Stock` INT NOT NULL,
  `Photo` BLOB NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`Articles_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luaWave`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luaWave`.`Cart` ;

CREATE TABLE IF NOT EXISTS `luaWave`.`Cart` (
  `Cart_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT 'DEFAULT NULL',
  `Code_postal` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Cart_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luaWave`.`Rental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luaWave`.`Rental` ;

CREATE TABLE IF NOT EXISTS `luaWave`.`Rental` (
  `Rental_id` INT NOT NULL AUTO_INCREMENT,
  `Articles_id` INT NOT NULL,
  `Cart_id` INT NOT NULL,
  `rental_date` DATETIME NOT NULL,
  `return_date` DATETIME NOT NULL,
  `Quantity` INT NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`Rental_id`, `Articles_id`, `Cart_id`),
  CONSTRAINT `Articles_id`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `luaWave`.`Articles` (`Articles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cart_id`
    FOREIGN KEY (`Cart_id`)
    REFERENCES `luaWave`.`Cart` (`Cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luaWave`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `luaWave`.`Staff` ;

CREATE TABLE IF NOT EXISTS `luaWave`.`Staff` (
  `Staff_id` INT NOT NULL AUTO_INCREMENT,
  `Articles_id` INT NOT NULL,
  `Cart_id` INT NOT NULL,
  `Rental_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(10) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(15) NULL DEFAULT 'DEFAULT NULL',
  `Address` VARCHAR(100) NULL DEFAULT 'DEFAULT NULL',
  `Active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Staff_id`, `Articles_id`, `Cart_id`, `Rental_id`),
  CONSTRAINT `Articles_id`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `luaWave`.`Articles` (`Articles_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cart_id`
    FOREIGN KEY (`Cart_id`)
    REFERENCES `luaWave`.`Cart` (`Cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Rental_id`
    FOREIGN KEY (`Rental_id`)
    REFERENCES `luaWave`.`Rental` (`Rental_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
